### ISSUE TITLE
TypeError: Cannot read property 'pipesCount' of undefined

### ISSUE THREAD

**Issue by calvinmetcalf** [archiverjs/node-zip-stream#26]
```bash
 error TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (/path/to/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (/path/to/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (/path/to/node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (/path/to/node_modules/zip-stream/index.js:138:49)
```

my code that's calling it is pretty strait forward

```js
function write (zip, stream, name) {
  return new Promise((resolve, reject) => {
    zip.entry(stream, {
      name: path.basename(name)
    }, function (err) {
      if (err) {
        return reject(err)
      }
      resolve()
    })
  })
}
```

from what I can tell `DeflateCRC32Stream` is not a real stream for some reason and I'm pretty stumped, ideas ?

**Comment by ctalkington** [comment]
related to issues with node v8  

https://github.com/archiverjs/node-archiver/issues/236

**Comment by himharsh1997** [comment]
This issue I'm facing in nodejs12 while deployment in bitbucket.
